name: Automatic Revert

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

permissions:
  actions: write
  contents: write

jobs:
  revert-commit:
    if: github.event.commits[0].author.name != github.repository_owner
    runs-on: ubuntu-latest
    steps:
      - name: Check user name
        run:
          echo "Author name = ${{github.event.commits[0].author.name}}"
          echo "Repo owner name = ${{github.repository_owner}}"
          echo "Repo owner id = ${{github.repository_owner}}"
          echo "Actor = ${{github.actor}}"
          echo "Trigger actor = ${{github.triggering_actor}}"
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Automatic Revert
        uses: ideabreeding-projects/auto-revert@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
