name: Automatic Revert

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  revert-commit:
    if: github.actor_id != github.repository_owner_id
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Automatic Revert
        uses: ideabreeding-projects/auto-revert@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
